feat: 使用接口上传
FEMessage/upload-to-ali pull request #119
Opened 2019-11-29 10:09 UTC by donaldshen

## Why
之前的上传方式使得 oss 的 key & secret 暴露在前端。十分危险。

## How
以后必须使用以下两种方式上传：
1. 传入 action 作为上传地址。上传地址接受以 bucket & file 作为 formData 的参数的 POST 请求，返回数据格式：
```js
{
  payload: {
    name: '文件名',
    url: '上传后的地址',
  }
}
```
2. 传入 request 函数。接受 file 类型，返回上传地址

## Test
to be continue

2019-11-29 11:04 UTC, donaldshen commented on src/upload-to-ali.vue
> +      default: process.env.ACTION
考虑：
1. 只从 prop 传入，设为 required
2. UPLOAD_ACTION

2019-11-29 11:05 UTC, donaldshen commented on src/upload-to-ali.vue
> +      default: process.env.OSS_DIR || 'hello/world'
```suggestion
      default: process.env.OSS_DIR
```

2019-11-29 11:12 UTC, donaldshen commented on src/upload-to-ali.vue
> +        // if (this.customDomain) {
考虑：
1. 移除 customDomain
2. 接口增加这个功能

2019-11-29 11:13 UTC, donaldshen commented on src/upload-to-ali.vue
> -        'bucket',
考虑在组件里声明可用的 bucket 选项

2019-11-29 11:16 UTC, donaldshen commented on src/upload-to-ali.vue
> +        //   : files[i]
考虑：
1. 移除 compress 功能
2. 尝试把 blob 转回 File 再试一下

2019-12-02 09:39 UTC, levy9527 requested changes

2019-12-02 09:39 UTC, levy9527 commented on src/upload-to-ali.vue
> +      default: process.env.ACTION
对，叫UPLOAD_ACTION

2019-12-02 09:39 UTC, levy9527 commented on src/upload-to-ali.vue
> +      default: process.env.OSS_DIR
恢复

2019-12-02 09:39 UTC, levy9527 commented on src/upload-to-ali.vue
> +        formData.append('image', file)
file

2019-12-02 09:39 UTC, levy9527 commented on src/upload-to-ali.vue
> +          xhr.send(formData)
异常处理呢

2019-12-03 13:09 UTC, donaldshen commented on src/upload-to-ali.vue
> +          const xhr = new XMLHttpRequest()
可能容易受到攻击。使用axios更好
@雷明

2019-12-04 09:15 UTC, merged

2019-12-04 09:16 UTC, levy9527 commented
@all-contributors add @donaldshen test